### ISSUE TITLE
Too minor change

### ISSUE THREAD

**Issue by alam-R** [bobonis/gb_emu#74]
```
int address_map;

switch (address >> 12){                 /* Get most significant 4 bits */
    case 0x4 ... 0x7:                   /* switchable ROM bank */
        address_map = address - 0x4000;
        address_map = address_map + (0x4000 * active_ROM_bank); //move address space to correct Memory Bank
        temp = cart_ROM[address_map];
```

do we really need this local address_map??

check 
        case 0xA ... 0xB:                   /\* switchable RAM bank */
            address -= 0xA000;
            address += 0x2000 \* active_RAM_bank; //move address space to correct RAM Bank
            temp = cart_RAM[address];
            break;

and perhaps we will change to

```
    case 0x4 ... 0x7:                   /* switchable ROM bank */
        address -= 0x4000;
        address += 0x4000 * active_ROM_bank; //move address space to correct Memory Bank
        temp = cart_ROM[address];
        break;
```

**Comment by bobonis** [comment]
We definitely need this, I've spent many hours debugging this issue. :rage: 
Have a look at the following example:  
active_ROM_bank = 11
address += 0x4000 \* active_ROM_bank;
address should be 0x16000 but.. it's an unsigned short, that means only 16 bits long and the value is truncated to 0x6000 !!

**Comment by alam-R** [comment]
Hehehehe, you are absolutely right.
Let's consider it then as a closed issue!
