### ISSUE TITLE
MBC2 Japan Games

### ISSUE THREAD

**Issue by bobonis** [bobonis/gb_emu#79]

**Comment by bobonis** [comment]
Could you please name some Japan games that are problematic?

**Comment by alam-R** [comment]
Daisenryaku (Japan) and Dragon Ball Z

**Comment by alam-R** [comment]
For the first one, when you press START button, it seems that emulator falls in a loop and nothing can stop it :P...

**Comment by bobonis** [comment]
Please have a look at the changes I did to the code. Waiting for feedback!

**Comment by alam-R** [comment]
ADD AFTER memory.c L 651  
  if (MBC2){
            if (RAM_bank_enabled){
                if (( pos >= 0xA000 ) && ( pos <= 0xA1FF )){
                      //printf(PRINT_RED "[DEBUG] Now we will write to SRAM" PRINT_RESET"\n");
                      pos &= 0x1FF;
                      /\* Only the 4 lower bits are used, the upper bits should be ignored */
                      memory_SRAM[pos] = value & 0x0F;
                      sram_active = 1;
                      //printf(PRINT_MAGENTA "[DEBUG] SRAM value =  %d and SRAM position = %d" PRINT_RESET"\n",memory_SRAM[pos],pos);
                }
             else {
                 memory[pos] = value;
             }
            }
        }
        else{
            if (RAM_bank_enabled){
                pos -= 0xA000;
                pos += 0x2000 \* active_RAM_bank; //move address space to correct RAM Bank
                cart_RAM[pos] = value;
            }
        }
    }

**Comment by bobonis** [comment]
I added the RAM enable check, and fixed the input. No more broken graphics for Dragonball!!! (I'm not sure how this had an effect on graphics but anyway :p ) You will notice though more broken graphics during game, like the bottom half of the screen is corrupted.. The other game is a hard nut...

**Comment by alam-R** [comment]
It is so fucking weird...:P
Yes I have noticed them before (eg. dialogues of goku and picolo).
Perhaps if we identify the root cause of Daisenryaku...

**Comment by bobonis** [comment]
Daisenryaku should work if we change the value written at 0xC0B1 from 0 to 1. It changes from a serial interrupt after the start button press.

**Comment by bobonis** [comment]
Finally, the game that gave me nightmares have been troubleshooted! DRAGONBALL seems playable! (Ofc we have to learn some Japanese but anyway)

There have been two issues with this:
1) There was a problem with the Window display, causing the bottom half of the screen to not be drawn. There are limits that I did never take into considaration.

``` c
    if (testBit(LCDC,5) == TRUE){         //Window Display Enable (0=Off, 1=On)
        /* start new handle limits */
        if (memory[WX] <= 166 && memory[WY] <= 143){
        /* end new */
            if (gpustate.line >= memory[WY]){ //Current scanline is after window position
                using_window = TRUE;

                posY = gpustate.line - windowY;
            }
        }
    }
```

2) Some distorted graphics at the menu were caused by sram being initialized to zero instead of 0xFF.

**Comment by bobonis** [comment]
Daisenryaku has some window Issues...

**Comment by bobonis** [comment]
Daisenryaku has been fixed! Closing for now!
